# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17f157816341188a56ad0a5ecc0394c71adc1f6d9d916f5bbf8889e5d4d88684a0dd6dbfff4c2b19bf45c9501f0c16da898fee6d3d817fc9feab01d4b2442b0c

test:
  secret_key_base: b608d37e30458c9cc7ef545ea7f8a469b28373e7480366f456173a5a5098dd906d3546c21dcedeca531233436cd497d919dc6a8967acfc16e438700e51692690

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: c63b7e2fcac9e5d73b1c0b79b2071c829dcedea5266cbb5084eef32e4b83e138173b4091738c01d3ea2bebc3aec3c1c746591f8f3ae93faa96eb571f19f4b44a
